base:
  config:
    oauth:
      hostname: localhost
      port: 9001
    nacos:
      hostname: 116.63.136.7
      port: 8848
spring:
  application:
    name: cloud-message
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
    stream:
      rocketmq:
        binder:
          name-server: 116.63.136.7:9876
      bindings:
        admin-login-log-topic: {destination: admin-login-log-topic, content-type: application/json}
security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token
dubbo:
  scan:
    base-packages: cn.yxvk.myshop.plus.cloud.prodcer
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://116.63.136.7:8848
    port: 80
server:
  port: 10002
management:
  endpoints:
    web:
      exposure:
        include: "*"